config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  put 'boards/:board_id/lists/:id/change_priority_up', to: 'lists#update_list_priority', as: 'update_list_priority'
  put 'boards/:board_id/lists/:id/change_priority_down', to: 'lists#downdate_list_priority', as: 'downdate_list_priority'

  resources :boards do
    resources :lists
  end

  scope 'lists/:list_id', as: 'list' do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  validates :priority, presence: true
  belongs_to :board
  has_many :tasks, dependent: :destroy

  def self.by_priority
    order(:priority)
  end

  def is_first?
    self.priority === 0
  end

  def is_last?
    
  end

  def self.set_priority_on_creation
    @list = @board.lists.new(list_params)

    max = @board.lists.maximum('priority')
    @list.priority = max + 1
  end

  def self.move_up
    list_to_move_down = @board.lists.find_by(priority: @list.priority - 1)
    @list.update(priority: list_to_move_down.priority) #delete a list, the rest of the numbers do not change
    list_to_move_down.update(priority: list_to_move_down.priority + 1)
  end

  def self.move_down
    list_to_move_up = @board.lists.find_by(priority: @list.priority + 1)
    @list.update(priority: list_to_move_up.priority) #delete a list, the rest of the numbers do not change
    list_to_move_up.update(priority: list_to_move_down.priority - 1)
  end

end

app/models/task.rb
class Task < ApplicationRecord
  validates :body, presence: true
  validates :priority, presence: true
  belongs_to :list

  def self.by_priority
    order(:priority)
  end

  def self.set_priority_on_creation
    @task = @list.tasks.new(task_params)

    max = @list.tasks.maximum('priority')
    @task.priority = max + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :set_board, only: [:show, :update, :edit, :destroy]

  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = Board.new
    render 'form'
  end

  def edit
    render 'form'
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to boards_path
    else
      render :form
    end
  end

  def update
    if @board.update(board_params)
      redirect_to @board
    else
      render :form
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy, :update_list_priority, :downdate_list_priority]

  def index
    @lists = @board.lists
    render :show
  end

  def show
  end

  def new
    @list = List.new
    render :form
  end

  def edit
    render :form
  end

  def create
    set_priority_on_creation(@board)

    if @list.save
      redirect_to board_path(@board)
    else
      render :form
    end
  end

  def update
    if @list.update(list_params)
      redirect_to board_path(@board)
    else
      render :form
    end
  end

  def destroy
    destroyed = @list.destroy

    @board.lists.each do |list|
      if list.priority > destroyed.priority
        list.priority = list.priority - 1
      end
      list.save
    end

    redirect_to board_path(@board)
  end

  def update_list_priority
    # move_up(@board)
    list_to_move_down = @board.lists.find_by(priority: @list.priority - 1)
    @list.update(priority: list_to_move_down.priority) #delete a list, the rest of the numbers do not change
    list_to_move_down.update(priority: list_to_move_down.priority + 1)

    redirect_to board_path(@list.board_id)
  end

  def downdate_list_priority
    list_to_move_up = @board.lists.find_by(priority: @list.priority + 1)
    @list.update(priority: list_to_move_up.priority) #delete a list, the rest of the numbers do not change
    list_to_move_up.update(priority: list_to_move_up.priority - 1)

    redirect_to board_path(@list.board_id)
  end

  private
  def set_list
    @list = List.find(params[:id])
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title, :priority)
  end
end

app/controllers/tasks_controller.rb
require 'pry'

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy, :update]
  before_action :set_list

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
    render :form
  end

  def edit
    render :form
  end

  def create
    # set_priority_on_creation(@list)
    @task = @list.tasks.new(task_params)
    

    if @task.save
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :form
    end
  end

  def edit
    render :form
  end

  def update
    if @task.update(task_params)
      redirect_to board_list_path(@list.board_id, @list)
    else
      render :form
    end
  end

  def destroy
    @task.destroy
    redirect_to board_list_path(@list.board_id, @list)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def task_params
      params.require(:task).permit(:body, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/form.html.erb
<h1><%= @board.id ? 'Edit board' : 'Create board' %></h1>
<hr/>

<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h1>Boards</h1>
<%= link_to 'Create a new board', new_board_path%>
<hr />
<ul>
  <% @boards.each do |board| %>
  <li> <%= link_to board.title, board_path(board) %> </li>
  <br />
  <% end %>
</ul>

app/views/boards/show.html.erb
<h1>Board: <%= @board.title %></h1>
<%= link_to 'Edit board', edit_board_path(@board) %>
<%= link_to 'Delete board', board_path(@board), method: :delete %>
<hr />

<h2>Lists</h2>
<%= link_to 'Create a new list', new_board_list_path(@board) %>
<br />
<ul>
  <% @board.lists.by_priority.each do |list| %>
    <li>
      <%= list.title %>
      <%= list.priority %>
      <p>
        <% if list.is_first? %>
          <%= link_to 'move down', downdate_list_priority_path(@board, list), method: :put %>
        <% end %>
        <% highest = @board.lists.maximum('priority') %>
        <% if list.priority == highest %>
          <%= link_to 'move up', update_list_priority_path(@board, list), method: :put %>
        <% end %>
        <% if !list.is_first? && list.priority != highest %>
          <%= link_to 'move up', update_list_priority_path(@board, list), method: :put %>
          <%= link_to 'move down', downdate_list_priority_path(@board, list), method: :put %>
        <% end %>
        
        <%= link_to 'Show tasks', board_list_path(@board, list) %>
        <%= link_to 'edit list', edit_board_list_path(@board, list) %>
        <%= link_to 'delete list', board_list_path(@board, list), method: :delete %>
      </p>
    </li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/lists/form.html.erb
<h1><%= @list.id ? 'Edit list' : 'Create list' %></h1>
<hr/>

<%= form_for [@board, @list] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true, autofocus: true %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<hr />

<h2>Tasks</h2>
<%= link_to 'Add a new task', new_list_task_path(@list) %>
<br />
<ul>
  <% @list.tasks.by_priority.each do |task| %>
    <li>
      <%= task.body %>
      <%= task.priority %>
      <p>
        <%= link_to 'edit task', edit_list_task_path(@list, task) %>
        <%= link_to 'delete task', list_task_path(@list, task), method: :delete %>
      </p>
    </li>
  <% end %>
</ul>

app/views/tasks/form.html.erb
<h1><%= @task.id ? 'Edit task' : 'Create task' %></h1>
<hr/>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, required: true %>
  <br />
  <%= f.label :priority %>
  <%= f.text_field :priority, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>